// Concurrency limits
export const PARALLEL_CONCURRENCY = 20;
export const DIR_TRAVERSAL_CONCURRENCY = 8;

// Timeout limits (in milliseconds)
export const REGEX_MATCH_TIMEOUT_MS = 100; // Per-line regex match timeout to prevent ReDoS hangs

// Size limits (in bytes)
export const MAX_SEARCHABLE_FILE_SIZE = 1024 * 1024; // 1MB
export const MAX_TEXT_FILE_SIZE = 10 * 1024 * 1024; // 10MB default for text files
export const MAX_MEDIA_FILE_SIZE = 50 * 1024 * 1024; // 50MB default for media files
export const MAX_LINE_CONTENT_LENGTH = 200;
export const BINARY_CHECK_BUFFER_SIZE = 512; // Increased for better accuracy

// Default limits for operations
export const DEFAULT_MAX_DEPTH = 10;
export const DEFAULT_MAX_RESULTS = 100;
export const DEFAULT_TOP_N = 10;
export const DEFAULT_TREE_DEPTH = 5;

// Known text file extensions for fast-path binary detection
export const KNOWN_TEXT_EXTENSIONS = new Set([
  '.ts',
  '.tsx',
  '.js',
  '.jsx',
  '.mjs',
  '.cjs',
  '.json',
  '.jsonc',
  '.json5',
  '.md',
  '.mdx',
  '.markdown',
  '.txt',
  '.text',
  '.log',
  '.html',
  '.htm',
  '.xhtml',
  '.css',
  '.scss',
  '.sass',
  '.less',
  '.styl',
  '.yaml',
  '.yml',
  '.xml',
  '.xsl',
  '.xslt',
  '.svg',
  '.sh',
  '.bash',
  '.zsh',
  '.fish',
  '.ps1',
  '.psm1',
  '.psd1',
  '.bat',
  '.cmd',
  '.py',
  '.pyw',
  '.pyi',
  '.pyx',
  '.rb',
  '.rake',
  '.gemspec',
  '.go',
  '.mod',
  '.sum',
  '.rs',
  '.c',
  '.h',
  '.cpp',
  '.hpp',
  '.cc',
  '.hh',
  '.cxx',
  '.hxx',
  '.java',
  '.kt',
  '.kts',
  '.scala',
  '.groovy',
  '.gradle',
  '.swift',
  '.php',
  '.phtml',
  '.sql',
  '.mysql',
  '.pgsql',
  '.graphql',
  '.gql',
  '.vue',
  '.svelte',
  '.astro',
  '.toml',
  '.ini',
  '.cfg',
  '.conf',
  '.config',
  '.env',
  '.env.local',
  '.env.development',
  '.env.production',
  '.gitignore',
  '.gitattributes',
  '.npmignore',
  '.dockerignore',
  '.editorconfig',
  '.prettierrc',
  '.eslintrc',
  '.lock', // package-lock.json, yarn.lock, etc. are text
  '.csv',
  '.tsv',
  '.rst',
  '.asciidoc',
  '.adoc',
  '.tex',
  '.latex',
  '.bib',
  '.r',
  '.R',
  '.rmd',
  '.lua',
  '.pl',
  '.pm',
  '.perl',
  '.asm',
  '.s',
  '.dart',
  '.elm',
  '.ex',
  '.exs',
  '.erl',
  '.hrl',
  '.hs',
  '.lhs',
  '.clj',
  '.cljs',
  '.cljc',
  '.edn',
  '.lisp',
  '.cl',
  '.el',
  '.ml',
  '.mli',
  '.fs',
  '.fsi',
  '.fsx',
  '.nim',
  '.v',
  '.sv',
  '.vhd',
  '.vhdl',
  '.proto',
  '.tf',
  '.tfvars',
  '.hcl',
  '.cmake',
  '.makefile',
  '.mk',
  '.dockerfile',
  '.containerfile',
]);

// Known binary file extensions for fast-path binary detection
export const KNOWN_BINARY_EXTENSIONS = new Set([
  // Images
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.webp',
  '.ico',
  '.bmp',
  '.tiff',
  '.tif',
  '.psd',
  '.ai',
  '.eps',
  '.raw',
  '.cr2',
  '.nef',
  '.heic',
  '.heif',
  '.avif',
  // Audio
  '.mp3',
  '.wav',
  '.flac',
  '.aac',
  '.ogg',
  '.wma',
  '.m4a',
  '.opus',
  '.aiff',
  // Video
  '.mp4',
  '.avi',
  '.mov',
  '.wmv',
  '.flv',
  '.mkv',
  '.webm',
  '.m4v',
  '.mpeg',
  '.mpg',
  // Archives
  '.zip',
  '.tar',
  '.gz',
  '.bz2',
  '.xz',
  '.7z',
  '.rar',
  '.cab',
  '.iso',
  '.dmg',
  // Executables & Libraries
  '.exe',
  '.dll',
  '.so',
  '.dylib',
  '.a',
  '.lib',
  '.o',
  '.obj',
  '.app',
  '.msi',
  '.deb',
  '.rpm',
  '.apk',
  '.ipa',
  // Fonts
  '.ttf',
  '.otf',
  '.woff',
  '.woff2',
  '.eot',
  // Documents (binary formats)
  '.pdf',
  '.doc',
  '.docx',
  '.xls',
  '.xlsx',
  '.ppt',
  '.pptx',
  '.odt',
  '.ods',
  '.odp',
  // Databases
  '.sqlite',
  '.sqlite3',
  '.db',
  '.mdb',
  '.accdb',
  // WebAssembly
  '.wasm',
  // Other binary
  '.bin',
  '.dat',
  '.pak',
  '.bundle',
  '.class',
  '.pyc',
  '.pyo',
  '.node',
  '.napi',
  // Source maps (can be large and not useful for text search)
  '.map',
]);

/**
 * Get the MIME type for a file extension.
 * Returns 'application/octet-stream' for unknown extensions.
 *
 * @param ext - File extension including the dot (e.g., '.png')
 * @returns The MIME type string
 */
export function getMimeType(ext: string): string {
  return MIME_TYPES[ext.toLowerCase()] ?? 'application/octet-stream';
}

// MIME type mappings for media files
export const MIME_TYPES: Record<string, string> = {
  // Images
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.bmp': 'image/bmp',
  '.tiff': 'image/tiff',
  '.tif': 'image/tiff',
  '.avif': 'image/avif',
  '.heic': 'image/heic',
  '.heif': 'image/heif',
  // Audio
  '.mp3': 'audio/mpeg',
  '.wav': 'audio/wav',
  '.ogg': 'audio/ogg',
  '.flac': 'audio/flac',
  '.aac': 'audio/aac',
  '.m4a': 'audio/mp4',
  '.wma': 'audio/x-ms-wma',
  '.opus': 'audio/opus',
  // Video
  '.mp4': 'video/mp4',
  '.webm': 'video/webm',
  '.avi': 'video/x-msvideo',
  '.mov': 'video/quicktime',
  '.wmv': 'video/x-ms-wmv',
  '.mkv': 'video/x-matroska',
  '.flv': 'video/x-flv',
  // Documents
  '.pdf': 'application/pdf',
  // Common text (best-effort)
  '.txt': 'text/plain',
  '.log': 'text/plain',
  '.md': 'text/markdown',
  '.markdown': 'text/markdown',
  '.json': 'application/json',
  '.jsonc': 'application/json',
  '.xml': 'application/xml',
  '.yaml': 'text/yaml',
  '.yml': 'text/yaml',
  '.html': 'text/html',
  '.htm': 'text/html',
  '.css': 'text/css',
  '.js': 'text/javascript',
  '.mjs': 'text/javascript',
  '.cjs': 'text/javascript',
  '.ts': 'text/typescript',
  '.tsx': 'text/typescript',
  // Archives
  '.zip': 'application/zip',
  '.tar': 'application/x-tar',
  '.gz': 'application/gzip',
  '.7z': 'application/x-7z-compressed',
  '.rar': 'application/vnd.rar',
  // Fonts
  '.ttf': 'font/ttf',
  '.otf': 'font/otf',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  // Other
  '.wasm': 'application/wasm',
};
